on:
  push:
    branches:
      - 'ussen_*'
name: ussen deployment
jobs:
  build:
    name: maddox/actions/ssh@6fc6694b013badc932fb2a6ec6edfa4e629254cf
    runs-on: ubuntu-latest
    steps:
    - name: Notify start
      uses: Ilshidur/action-slack@1ee0e72f5aea6d97f26d4a67da8f4bc5774b6cc7
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: 'deployment started: {{ GITHUB_REF }}'
    - name: ssh
      uses: maddox/actions/ssh@6fc6694b013badc932fb2a6ec6edfa4e629254cf
      env:
        HOST: ${{ secrets.HOST }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        USER: ${{ secrets.USER }}
      with:
        args: ./deploy.sh ${{ github.ref }}
    - name: Notify end
      uses: Ilshidur/action-slack@1ee0e72f5aea6d97f26d4a67da8f4bc5774b6cc7
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: 'deployment finished: {{ GITHUB_REF }}'
